spring:
  application:
    name: acp-cw1
  jackson:
    serialization:
      indent_output: false
  datasource:
    url: ${ACP_POSTGRES:jdbc:postgresql://localhost:5432/acp}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO

acp:
  postgres: ${ACP_POSTGRES:jdbc:postgresql://localhost:5432/acp}
  s3: ${ACP_S3:http://localhost:4566}
  dynamodb: ${ACP_DYNAMODB:http://localhost:4566}
  url-endpoint: ${ACP_URL_ENDPOINT:http://localhost:8081}
  sid: ${ACP_SID:}
